name: Remote Dispatch Action Responder

on:
  workflow_dispatch: { }

jobs:
  event-source:
    runs-on: ubuntu-20.04
    steps:
      -
        run: |
          set +ex
          curl -X POST https://api.github.com/repos/tbauchsp-ampeersenergy/experiment-gh-workflow-receiver/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u "${ACCESS_TOKEN?}" \
            --data '{"event_type": "lorem-ipsum", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

